ALTER TABLE users
    ADD COLUMN IF NOT EXISTS avatar_url VARCHAR(512) DEFAULT '',
    ADD COLUMN IF NOT EXISTS github_url VARCHAR(256) DEFAULT '',
    ADD COLUMN IF NOT EXISTS bio VARCHAR(500) DEFAULT '';

ALTER TABLE rooms
    ADD COLUMN IF NOT EXISTS description VARCHAR(500) DEFAULT '',
    ADD COLUMN IF NOT EXISTS is_private BOOLEAN DEFAULT false;
