server:
  AppVersion: 1.0.0
  Port: :8080
  Mode: Development
  JwtSecretKey: futodamaforever
  CookieName: jwt-token
  ReadTimeout: 5
  WriteTimeout: 5
  SSL: false
  CtxDefaultTimeout: 12
  CSRF: true
  Debug: false

logger:
  Development: true
  DisableCaller: false
  DisableStacktrace: false
  Encoding: console
  Level: info

postgres:
  PostgresqlHost: localhost
  PostgresqlPort: 5432
  PostgresqlUser: fedor
  PostgresqlPassword: postgres
  PostgresqlDbname: code_together
  PostgresqlSslmode: false
  PgDriver: pgx

redis:
  RedisAddr: localhost:6379
  RedisPassword:
  RedisDb: 0
  RedisDefaultdb: 0
  MinIdleConns: 200
  PoolSize: 12000
  PoolTimeout: 240
  Password: ""
  DB: 0

cookie:
  Name: jwt-token
  MaxAge: 86400
  Secure: false
  HttpOnly: true

session:
  Name: session-id
  Prefix: api-session
  Expire: 3600
